import type { Metadata } from 'next'
import Header from './Header'
import Swiper from './Swiper'
export const metadata: Metadata = {
  title: 'Shopping Wood',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <div className=" flex justify-center   mt-6 w-[99%] sm:w-[80%] m-auto">
      <Swiper/>
        {children}

    </div>
  )
}
